### ISSUE TITLE
AttributeError: 'AHT20' object has no attribute 'e_status'

### ISSUE THREAD

**Issue by tonygo** [PaulskPt/galactic_unicorn_alt_lower_case_tests#1]
Hi Paulus,

Thanks for all the work you have done on this. I've just tried to run it and got this output and error:

>>> %Run -c $EDITOR_CONTENT
Starting tests...
by Tony Goodhew (@tonygo2)
modified by Paulus Schulinck (@PaulskPt)
TonyGo2 test
Temp & Hum test
Traceback (most recent call last):
  File "<stdin>", line 403, in <module>
  File "<stdin>", line 391, in doit
  File "<stdin>", line 336, in temp_sensor_test
AttributeError: 'AHT20' object has no attribute 'e_status'
>>> 

I'm not sure what I have done wrong. Did you modify the aht0x.py lib? The sensor is plugged into QT socket 1 and the green LED is lit.

**Comment by tonygo** [comment]
Just found where you updated the aht0x.py library. All working now.

**Comment by PaulskPt** [comment]
Hi Tony,
Thank you for your reply. Yes, I updated the aht0x.py file. I'm glad it's working now on your side.
The 'hotplug' algorithm is 'work-in-progress'. I have it working in CircuitPython (it is added to the examples of CircuitPython, see: [hotplug](https://github.com/adafruit/Adafruit_CircuitPython_DisplayIO_Layout/tree/main/examples/hotplug_sensor_examples). I have to study again that part to see if I can get it totally reliable in my mod of your MicroPython example for the Galactic Unicorn.

**Comment by PaulskPt** [comment]
The 'hotplug' algorithm is working OK now. Expect no more changes needed in this algorithm
Since you wrote that all is working now, I close this issue.
